dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - aave/protocol-v2@1.0.1

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - '@aave=aave/protocol-v2@1.0.1'


dotenv: .env

networks:
  default: development
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e' # PriceFeed contract address on rinkeby
    verify: True
  mainnet-fork: #brownie networks add development mainnet-fork cmd=ganache-cli host=http://127.0.0.1 fork='https://eth-mainnet.alchemyapi.io/v2/uQFH44NJvSW0ArYUTMAjWGiCVJ8eXhV4' accounts=10 mnemonic=brownie port=8545
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
    lending_pool_addresses_provider: '0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5'
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419' # PriceFeed contract address on Mainnet
    verify: False 
  mainnet-fork-dev: #brownie networks add development mainnet-fork-dev cmd=ganache-cli host=http://127.0.0.1 fork='https://eth-mainnet.alchemyapi.io/v2/uQFH44NJvSW0ArYUTMAjWGiCVJ8eXhV4' accounts=10 mnemonic=brownie port=8545
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419' # PriceFeed contract address on Mainnet
    verify: False 
  kovan:
    weth_token: '0xd0a1e359811322d97991e03f863a0c30c2cf029c'
    eth_usd_price_feed: '0xffffffffffff' # PriceFeed contract address on kovan
    lending_pool_addresses_provider: '0x88757f2f99175387aB4C6a4b3067c77A695b0349'
    verify: True
  ganache-local:
    verify: False
  
  development:
    verify: False

wallets: 
  from_key: ${PRIVATE_KEY}